import type { DeckStudyMode, StudyMode } from "./types";

/** ユーザー向け UI 文言 SSOT — 正本: docs/spec/glossary.md */
export const copy = {
  nav: {
    home: "ホーム",
    deckStudy: "デッキ学習",
    leitner: "スマート学習",
    settings: "設定",
    homeHint: "デッキ",
    deckStudyHint: "フラッシュカードで学習",
    leitnerHint: "今日の復習",
    settingsHint: "設定",
  },
  topbar: {
    home: "ホーム",
    deckStudyDefault: "デッキ学習",
    leitnerDefault: "スマート学習",
    settings: "設定",
    sessionLabel: "復習中",
  },
  sidebar: {
    captureSection: "取込",
    textCapture: "テキスト",
    screenshotCapture: "スクショ",
    open: "サイドバーを開く",
    close: "サイドバーを閉じる",
    closeScrim: "サイドバーを閉じる",
  },
  tray: {
    reviewCount: (count: number) => `今日の復習: ${count}件`,
    openHome: "ホームを開く",
  },
  home: {
    currentDeck: "現在のデッキ",
    getStarted: "はじめに",
    pickDeck: "デッキを選びましょう",
    newDeckPlaceholder: "新しいデッキの名前",
    noDecksTitle: "デッキがありません",
    noDecksCopy: "上のフォームから最初のデッキを作成してください。",
    decksSection: "デッキ一覧",
    goToDeckStudy: "デッキ学習へ",
    metrics: {
      sectionLabel: "学習メトリクス",
      summaryEyebrow: "学習サマリー",
      deckEyebrow: "選択中デッキ",
      loading: "メトリクスを読み込み中…",
      todayStudy: "今日の学習",
      streak: "連続日数",
      globalMastery: "全体習熟度",
      globalBoxHeading: "全体の Box 分布",
      boxDistributionLabel: "Box 分布",
      masteryLabel: "習熟度",
      noCards: "カードがまだありません",
      deckEmpty: "カードを追加すると、このデッキの習熟度が表示されます",
      countValue: (count: number) => `${count} 回`,
      streakValue: (days: number) => `${days} 日`,
      percentValue: (percent: number) => `${percent}%`,
      todayStudyHint: (leitner: number, deck: number) =>
        `Leitner ${leitner} · デッキ学習 ${deck}`,
      deckDue: (count: number) => `${count} 件復習待ち`,
    },
  },
  deckScheduler: {
    sectionLabel: "スマート学習の間隔",
    title: "スマート学習の間隔",
    description:
      "学習ステップ（分〜時間）と復習間隔（日）を全デッキ共通で設定します。変更は次回採点から反映されます。",
    loading: "間隔設定を読み込み中…",
    learningStepsTitle: "学習ステップ",
    relearningStepsTitle: "再学習ステップ",
    reviewIntervalsTitle: "復習間隔（箱 2〜5）",
    singleIntervalsTitle: "採点別の間隔",
    hardIntervalLabel: "難しい",
    graduatingIntervalLabel: "卒業（正解で学習完了）",
    easyIntervalLabel: "簡単",
    immediateInterval: "今すぐ",
    stepLabel: (step: number) => `ステップ ${step}`,
    boxLabel: (box: number) => `箱 ${box}`,
    unitMinute: "分",
    unitHour: "時間",
    unitDay: "日",
    addStep: "ステップを追加",
    removeStep: "削除",
    save: "保存",
    reset: "デフォルトに戻す",
    saved: "保存しました",
    invalidConfig: "間隔の設定内容を確認してください。",
    saveFailed: "保存に失敗しました。もう一度お試しください。",
  },
  deckStudy: {
    hubTitle: "学習を始める",
    modesEyebrow: "学習モード",
    modesAriaLabel: "学習モード",
    shuffle: "シャッフル",
    back: "戻る",
    searchPlaceholder: "カードを検索...",
    cardPreview: "カードプレビュー",
    coverflowAria: "デッキカード",
    selectDeckTitle: "デッキが選択されていません",
    selectDeckCopy: "ホームでデッキを選んでから学習を始めてください。",
    emptyEyebrow: "デッキ学習",
    sessionRemaining: (remaining: number, total: number) => `残り ${remaining} / ${total}`,
    known: "覚えた",
    still: "まだ",
    sessionCompleteTitle: "このデッキの学習が完了しました",
    sessionCompleteCopy: "すべてのカードを覚えました。",
    sessionRestart: "もう一度",
    loadingSession: "カードを読み込み中…",
    loadError: "カードを読み込めませんでした",
    retryLoad: "再読み込み",
  },
  leitnerStudy: {
    hubTitle: "スマート学習",
    dueToday: (count: number) => `今日 ${count} 件`,
    dueBannerSuffix: "件が復習待ち",
    startAllHero: "復習を始める",
    startAllHint: "全デッキの復習予定をランダムに復習",
    deckDueHint: "デッキを選ぶと、そのデッキの復習予定だけ復習します",
    goFromHome: "スマート学習へ",
    sessionActiveLabel: "復習中",
    decksSection: "デッキ別",
    deckDue: (count: number) => `${count} 件`,
    back: "戻る",
    completeTitle: "今日のスマート学習は完了です",
    completeHint: "⌥⌘M / ⌥⌘S で新しいカードを追加できます。",
    deckSessionCompleteTitle: "このデッキの復習は完了しました",
    deckSessionCompleteCopy: (remaining: number) =>
      `他デッキにあと ${remaining} 件の復習があります。`,
    backToHub: "スマート学習に戻る",
    queueLoadError: "復習カードを読み込めませんでした",
    completionCheckError: "完了状態を確認できませんでした",
    loadingQueue: "復習カードを読み込み中…",
    retryLoad: "再読み込み",
    emptyEyebrow: "スマート学習",
    hint: "Space / クリック 答え · 1 もう一度 · 2 難しい · 3 正解 · 4 簡単",
    gradeAgain: "もう一度",
    gradeHard: "難しい",
    gradeGood: "正解",
    gradeEasy: "簡単",
  },
  studyModes: {
    flashcards: {
      label: "フラッシュカード",
      desc: "答えを確認しながら全カードを巡る",
    },
    learn: {
      label: "スマート学習",
      desc: "復習予定カードを出題",
    },
    write: {
      label: "書く",
      desc: "マスク部分を入力して思い出す",
    },
    test: {
      label: "テスト",
      desc: "4 択で正解を選ぶ",
    },
    match: {
      label: "マッチ",
      desc: "問題と答えのペアを組み合わせる",
    },
  } satisfies Record<
    StudyMode,
    { label: string; desc: string }
  >,
  cards: {
    sectionEyebrow: "カード",
    addSection: "カードの追加",
    addHint: "ホームでデッキを選んでからカードを追加してください。",
    composerHint: "テキストを入力し、マスクしたい部分を選択して + マスク",
    composerPlaceholder: "暗記したいテキストを入力...",
    composerSave: "カードを追加",
    composerSaving: "追加中...",
    emptyTitle: "カードがまだありません",
    emptyCopy: "上の入力欄から最初のカードを追加してください。",
    textCapture: "テキスト取込",
    screenshotCapture: "スクショ取込",
    kindText: "テキスト",
    kindQa: "Q&A",
    kindImage: "画像",
    previewAria: (kind: string) => `${kind} カードをプレビュー`,
    deleteTitle: "カードを削除しますか？",
  },
  capture: {
    text: "テキスト取込",
    screenshot: "スクショ取込",
  },
  editor: {
    deck: "デッキ",
    note: "メモ",
    notePlaceholder: "任意",
    createText: "暗記カード作成",
    editText: "テキストを編集",
    editTextTitle: "テキスト編集 ✦",
    createQa: "一問一答作成 ✦",
    editQa: "一問一答編集 ✦",
    editQaEyebrow: "Q&A を編集",
    editTextEyebrow: "テキストを編集",
    createImage: "暗記カード作成 ✦",
    editImage: "スクショ編集 ✦",
    qaToggle: "一問一答形式にする",
    qaExit: "問題文と解答を連結してマスク編集に戻す",
    questionLabel: "問題文",
    answerLabel: "解答",
    answerPlaceholder: "解答を入力...",
    maskCount: (count: number) => `${count} マスク`,
    addMask: "+ マスク",
    saveHint: "⌘Enter 保存 · Esc キャンセル",
    maskMode: "マスク",
    ocrMode: "OCR",
    zoomOut: "縮小",
    zoomIn: "拡大",
    maskColor: "マスクの色",
    removeMask: "マスクを削除",
    removeMaskTitle: "クリックで削除",
  },
  login: {
    eyebrow: "ログイン",
    title: "Google でログイン",
    googleButton: "Google で続ける",
    sessionExpired: "セッションの有効期限が切れました。再度ログインしてください。",
    brandDescription: "クラウドでデッキを同期し、どこからでも学習できます。",
  },
  settings: {
    shortcutsEyebrow: "ショートカット",
    shortcutsTitle: "ショートカット",
    permissionsEyebrow: "権限",
    permissionsTitle: "権限",
    studyEyebrow: "学習",
    studyTitle: "学習",
    schedulerEyebrow: "スマート学習",
    schedulerTitle: "スマート学習の間隔",
    maskEyebrow: "マスク",
    maskTitle: "マスク表示",
    studyNote:
      "「デッキ学習」では選択中デッキのカードをフラッシュカード等で学習できます。「スマート学習」では復習予定のカードを 4 段階評価で復習します。反復期間は上の「スマート学習の間隔」で全デッキ共通に設定できます。ホームではデッキ操作、デッキ学習タブではカードの編集・スター、デッキのエクスポート/インポートも利用できます。",
    maskNote:
      "復習時のマスクは Black で不透明表示されます。アクセントカラーは Chartreuse（#CEFF1A）です。",
    refreshPermissions: "権限状態を再確認",
    granted: "許可済み",
    denied: "未許可",
    openSettings: "設定を開く",
  },
  billing: {
    eyebrow: "課金",
    title: "プラン",
    currentPlan: (plan: string) => `現在のプラン: ${plan}`,
    upgradePro: "Pro にアップグレード",
    webOcrNote: "Web では OCR 取込は利用できません。",
  },
  account: {
    title: "アカウント",
    loggedInAs: (email: string) => `ログイン中: ${email}`,
  },
  writeMode: {
    emptyTitle: "書く問題がありません",
    emptyCopy: "テキストカードにマスクを追加すると、書くモードで出題されます。",
    completeEyebrow: "書く",
    promptEyebrow: "問題",
    answerPlaceholder: "答えを入力...",
    retry: "もう一度",
  },
  testMode: {
    emptyTitle: "テスト問題がありません",
    emptyCopy: "マスク付きカードが2枚以上あると、選択問題を生成できます。",
    completeEyebrow: "テスト",
    questionEyebrow: "問題",
    retry: "もう一度",
  },
  matchMode: {
    emptyTitle: "マッチ問題がありません",
    emptyCopy: "マスク付きカードが1枚以上必要です。",
    completeEyebrow: "マッチ",
    completeTitle: "すべて一致しました!",
    retry: "もう一度",
  },
  flashcardsMode: {
    emptyTitle: "カードがありません",
    emptyCopy: "カードを追加するか、別のデッキを選んでください。",
  },
  common: {
    answer: "解答",
    cancel: "キャンセル",
    search: "検索",
    deleteDeckTitle: "デッキを削除しますか？",
  },
  ai: {
    studyTitle: "AI に聞く",
    studyHint: "カードの内容について質問できます。",
    studyQuestionLabel: "質問",
    studyQuestionPlaceholder: "例: この用語をもっと詳しく教えて",
    studyPresetDetail: "もっと詳しく",
    studyPresetExample: "例を教えて",
    studySend: "送信",
    studySending: "送信中...",
    studyLoading: "回答を生成中...",
    studyAskButton: "AI に聞く",
    generateTitle: "AI で生成",
    generateHint: "ソーステキストから一問一答を自動生成します。",
    generateSourceLabel: "ソーステキスト",
    generateAction: "生成",
    generateLoading: "生成中...",
    generateApply: "この Q&A を使う",
    generateButton: "AI で生成",
    cardsGenerateTitle: "AI カード一括生成",
    cardsGenerateHint: "長文テキストまたは画像から Q&A カードをまとめて生成します。",
    cardsGenerateAddButton: "AI でカードを追加",
    cardsGenerateTabText: "テキスト",
    cardsGenerateTabImage: "画像",
    cardsGenerateUploadText: "ファイルを選ぶ",
    cardsGenerateUploadTextHint: ".txt / .md をアップロードできます",
    cardsGenerateDropzone: "画像をドロップ、またはクリックして選択",
    cardsGenerateDropzoneHint: "最大 5 枚 · JPEG / PNG / WebP",
    cardsGenerateCountLabel: "生成枚数",
    cardsGenerateTierLabel: "AI モード",
    cardsGenerateTierFast: "高速AI",
    cardsGenerateTierThinking: "熟考AI",
    cardsGenerateCredits: (remaining: number, cost: number) =>
      `残り ${remaining} クレジット（今回 ${cost}）`,
    cardsGenerateCreditsLoading: "クレジットを確認中…",
    cardsGenerateSelectAll: "すべて選択",
    cardsGenerateSaveSelected: (count: number) => `${count} 枚を保存`,
    cardsGenerateSaving: "保存中...",
    cardsGenerateSaved: (count: number) => `${count} 枚のカードを追加しました`,
    cardsGenerateEmptyCta: "AI でカードを追加",
    cardsGenerateImageUploading: "画像をアップロード中…",
    cardsGenerateImageError: "画像のアップロードに失敗しました",
    cardsGenerateNoSelection: "保存するカードを選択してください",
    cardsGeneratePartialSave: (saved: number, remaining: number) =>
      `${saved} 枚を保存しました。残り ${remaining} 枚は保存に失敗しました。再試行してください。`,
    errorUnavailable:
      "AI が利用できません。Cloudflare AI Gateway の設定を確認してください。",
    errorAuthFailed:
      "AI Gateway の認証に失敗しました。Settings の Create authentication token で発行したトークンを AI_GATEWAY_TOKEN に設定してください。",
    errorProviderUnavailable:
      "選択した AI モデルが利用できません。Unified Billing 非対応のモデル（DeepSeek 等）は Gateway にプロバイダ API キー（BYOK）を登録するか、対応モデルに変更してください。",
    errorPaymentRequired: "AI 機能は Pro プランで利用できます。",
    errorRateLimited: "リクエストが多すぎます。しばらく待ってから再試行してください。",
    errorGeneric: "AI の応答を取得できませんでした。",
  },
} as const;

export const studyModeList = (
  Object.entries(copy.studyModes) as [StudyMode, (typeof copy.studyModes)[StudyMode]][]
).map(([id, mode]) => ({ id, ...mode }));

export const deckStudyModeList = studyModeList.filter(
  (mode): mode is (typeof studyModeList)[number] & { id: DeckStudyMode } =>
    mode.id !== "learn",
);

export function cardKindLabel(kind: string): string {
  switch (kind) {
    case "text":
      return copy.cards.kindText;
    case "qa":
      return copy.cards.kindQa;
    case "image":
      return copy.cards.kindImage;
    default:
      return kind;
  }
}
